//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public decimal Price { get; set; }
        public int StatusID { get; set; }
        public string Author { get; set; }
        public int CategoryID { get; set; }
        public string ItemImage { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
    }
}
